services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    systemPackages:
      - gobject-introspection
      - libgirepository1.0-dev
      - build-essential
      - libglib2.0-dev
