services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y gobject-introspection libgirepository1.0-dev build-essential libglib2.0-dev && \
      pip install -r requirements.txt
    startCommand: python your_start_script.py
    plan: free
    autoDeploy: true
